pizza/config/urls.py
from django.contrib import admin
from django.urls import path, include
from order.views import create_order, create_model_order, index
from pizzas.views import pizza_detail_view
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('<slug:slug>', pizza_detail_view, name="pizza_detail"),
    path('create_order/', create_order, name="createorder"),
    path('createmodelorder/', create_model_order, name="createmodelorder"),
    path('__debug__/', include(debug_toolbar.urls)),
]

pizza/order/models.py
from django.db import models
from pizzas.models import PizzaModel
from django.utils.translation import gettext_lazy as _

# Create your models here.
class OrderModel(models.Model):
    class DeliveryStatus(models.TextChoices):
        PENDING = 'PEN', _('Pending')
        DELIVERED = 'DEL', _('Delivered')
    address = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    pizza_order = models.ManyToManyField(PizzaModel)
    delivery_status = models.CharField(max_length=3, choices=DeliveryStatus.choices, default=DeliveryStatus.PENDING)

    class Meta:
        verbose_name = "Orders"
        verbose_name_plural = "Orders"

    def __str__(self):
        return f'Some Address: {self.address}, Order: {", ".join([j.name for j in self.pizza_order.all()])}'

    def all_orders(self):
        return "\n".join([o.name for o in self.pizza_order.all()])

# class OrderProxy(OrderModel.pizza_order.through):
#     class Meta:
#         proxy = True

#     def __str__(self):
#         return str(self.ordermodel)

pizza/pizzas/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
# Create your models here.


class ToppingsModel(models.Model):
    name = models.CharField(max_length=55)

    class Meta:
        verbose_name = 'Toppings'
        verbose_name_plural = 'Toppings'

    def __str__(self):
        return self.name

class PizzaModel(models.Model):
    name = models.CharField(max_length=55)
    name_slug = models.SlugField(blank=True, null=True)
    toppings = models.ManyToManyField(ToppingsModel, verbose_name='toppings')

    class Meta:
        verbose_name = 'My pizza recipes'
        verbose_name_plural = 'Pizza recipes'

    def save(self, *args, **kwargs):
        if not self.name_slug:
            self.name_slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pizza_detail', kwargs={'slug': self.name_slug})

    def all_toppings(self):
        return "\n".join([t.name for t in self.toppings.all()])

    def __str__(self):
        return  f'{self.name}: {", ".join([topping.name for topping in self.toppings.all()])}'

# class ProxyPizza(PizzaModel.toppings.through):
#     class Meta:
#         proxy = True

#     def __str__(self):
#         return str(self.toppingsmodel)

pizza/order/forms.py
from django import forms
from pizzas.models import PizzaModel
from .models import OrderModel
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Button, Submit, Layout, Field, ButtonHolder

PIZZAS = [(f'{p.id}', f'{p.name}') for p in PizzaModel.objects.all()]
DEL_STATUS = [('Pen', 'Pending'), ('DEL', 'Delivered')]

class CreateForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-inline'
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Field('address'),
            Field('choice'),
            Field('delivery_status'),
            ButtonHolder (
                Submit('order', 'Order', css_class='btn btn-danger')
            )

        )

    address = forms.CharField(required=True)
    choice = forms.ChoiceField(
        choices=PIZZAS,
        help_text='If you wanna some extra. Send us <a href="#">message</a>',
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'pizzas'})
    )
    delivery_status = forms.ChoiceField(
        choices=DEL_STATUS
    )

class CreateOrderModelForm(forms.ModelForm):
    error_css_class = "error-field-class"
    required_css_class = "required-field-class"
    class Meta:
        model = OrderModel
        fields = ['address', 'pizza_order']
        widgets = {
            'address': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your address: '
            }),
            'pizza_order': forms.CheckboxSelectMultiple()
        }

pizza/order/views.py
from django.shortcuts import render, redirect
from pizzas.models import PizzaModel
from .models import OrderModel
from .forms import CreateForm, CreateOrderModelForm
from django.forms import modelformset_factory
# Create your views here.

def index(request):
    return render(request, 'index.html')
def create_order(request):
    order_form = CreateForm(request.POST or None)
    context = {
        'pizzas': PizzaModel.objects.all(),
        'order_form': order_form
    }
    if order_form.is_valid():
        address = order_form.cleaned_data.get('address')
        order = dict(order_form.data).get('choice')
        pizza_objects = [PizzaModel.objects.get(id=i) for i in order]
        new_order = OrderModel.objects.create(address=address)
        new_order.pizza_order.add(*pizza_objects)
        new_order.save()
        return redirect('createorder')
    return render(request, 'order/create_order.html', context=context)

def create_model_order(request, *args, **kwargs):
    model_form = CreateOrderModelForm(request.POST or None)
    OrderFormSet = modelformset_factory(OrderModel, form=CreateOrderModelForm, extra=2)
    model_form = OrderFormSet(
        request.POST or None,
        queryset=OrderModel.objects.none(),
        initial=[{'address': 'modelformset street'}]
        )
    # print(model_form.data)
    # if model_form.is_valid():
    #     model_form.save()
    #     return redirect('createmodelorder')
    context = {
        'pizzas': PizzaModel.objects.all(),
        'form': model_form
    }
    return render(request, 'order/create_model_order.html', context=context)

pizza/pizzas/views.py
from django.shortcuts import render
from .models import PizzaModel

# Create your views here.

def pizza_detail_view(request, *args, **kwargs):
    print(kwargs)
    pizza_obj = PizzaModel.objects.get(name_slug=kwargs.get('slug'))
    context = {'pizza_object': pizza_obj}
    return render(request, 'pizza/pizza_detail.html', context)

pizza/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    {% for data in test_data %}
        <ul>
            <li>{{ data }}</li>
        </ul>
    {% endfor %}
</body>
</html>

pizza/templates/order/create_model_order.html
<h1>Our Pizzas! So delicions</h1>

<ul>
    {% for pizza in pizzas %}
        <li>{{ pizza.name }}</li>
        <div>
            Ingredients
        </div>
        <ul>
            {% for ingredient in pizza.toppings.all %}
                <li>{{ ingredient }}</li>
            {% endfor %}
        </ul>
    {% endfor %}
    <form class="form" action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="place order">
    </form>
    <button class="more">add more pizza</button>
</ul>
<script>
    let pizza = document.querySelector('#id_pizza_order');
    let order = document.querySelector('.order');
    let more = document.querySelector('.more');
    let form = document.querySelector('.form');
    let body = document.querySelector('body')

    more.addEventListener('click', (e) => {
        e.preventDefault();
        p = document.createElement('p')
        l = document.createElement('label')
        l.setAttribute('for', 'id_choice')
        l.textContent = 'Choice: '
        cloned = pizza.cloneNode(true)
        p.append(l)
        p.append(cloned)
        form.insertBefore(p, order)

    });

</script>

pizza/templates/order/create_order.html
{% load crispy_forms_tags %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<h1>Our pizzas!</h1>

{% crispy order_form %}

<ul>
    {% for pizza in pizzas %}
        <li>
            <a href="/{{ pizza.name_slug }}">{{ pizza.name }}</a>
        </li>
        <div>
            <mark>Ingredients</mark>
        </div>
        <ul>
            {% for topping in pizza.toppings.all %}
                <li>{{ topping.name }}</li>
            {% endfor %}
        </ul>  
    {% endfor %}
    <!-- <form action="" method="post" class="form">
        {% csrf_token %}
        {{ order_form|crispy }}
        <button type="submit" class="btn btn-danger">Make order</button>
    </form> -->
    <button type="submit" class="btn btn-outline-danger">add more pizza</button>
    
</ul>
<script>
    let pizza = document.querySelector('.pizza');
    let order = document.querySelector('.order');
    let more = document.querySelector('.more');
    let form = document.querySelector('.form');
    let body = document.querySelector('body')

    more.addEventListener('click', (e) => {
        e.preventDefault();
        p = document.createElement('p')
        l = document.createElement('label')
        l.setAttribute('for', 'id_choice')
        l.textContent = 'Choice: '
        cloned = pizza.cloneNode(true)
        p.append(l)
        p.append(cloned)
        form.insertBefore(p, order)

    });

</script>

pizza/templates/pizza/pizza_detail.html
<h1>Pizza name</h1>
{{ pizza_object.name }}
<h1>Pizza ingredients</h1>